import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {ArrowRight,Check,FileText,Home,ShieldCheck,UploadCloud,Users,AlertTriangle,ChevronRight,LockKeyhole} from "lucide-react";
import "./styles.css";

const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
type Step="home"|"info"|"evidence"|"assessment"|"decision"|"review";
type Result={decision:string,reason:string,trace:any[],id:string,documents:any[],applicant:any};

function App(){
 const [step,setStep]=useState<Step>("home"),[name,setName]=useState(""),[dob,setDob]=useState(""),[income,setIncome]=useState(""),[residence,setResidence]=useState("");
 const [files,setFiles]=useState<File[]>([]),[caseId,setCaseId]=useState(""),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function start(){setError("");if(!name||!dob||!income||!residence){setError("Complete all required fields.");return}setBusy(true);try{const r=await fetch(API+"/api/applications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,dob,income:Number(income),residence})});if(!r.ok)throw Error(await r.text());const d=await r.json();setCaseId(d.id);setStep("evidence")}catch(e:any){setError("Could not reach the backend. Start FastAPI on port 8000.")}finally{setBusy(false)}}
 async function uploadAndProcess(){setError("");if(!files.length){setError("Choose at least one evidence document.");return}setBusy(true);try{for(const f of files){const fd=new FormData();fd.append("file",f);const r=await fetch(`${API}/api/applications/${caseId}/evidence`,{method:"POST",body:fd});if(!r.ok)throw Error(await r.text())}const p=await fetch(`${API}/api/applications/${caseId}/process`,{method:"POST"});if(!p.ok)throw Error(await p.text());setResult(await p.json());setStep("assessment")}catch(e:any){setError(e.message||"Evidence processing failed.")}finally{setBusy(false)}}
 async function review(){setStep("review")}
 return <div className="app"><header><button className="brand" onClick={()=>setStep("home")}><span>CG</span> ClearGov <b>Nexus</b></button><nav><button onClick={()=>setStep("home")}><Home size={16}/>Home</button><button onClick={()=>{setStep("review");setResult(null)}}><Users size={16}/>Reviewer Portal</button></nav></header>
 {step==="home"&&<><section className="hero"><div className="shade"/><div className="heroText"><div className="eyebrow">PUBLIC SERVICE APPLICATION</div><h1>From evidence<br/><i>to decision.</i></h1><p>Submit your information and supporting evidence. Understand what has been established, what needs attention, and what happens next.</p><button className="primary" onClick={()=>setStep("info")}>Start an application <ArrowRight/></button></div></section><section className="content"><div className="two"><div><small>HOW IT WORKS</small><h2>A clearer path through your application.</h2></div><p>ClearGov connects evidence to requirements, decisions to explanations, and uncertainty to human review.</p></div><div className="flow">{["Information","Evidence","Assessment","Decision","Next action"].map((x,i)=><div key={x}><b>0{i+1}</b><strong>{x}</strong><span>{["Enter your details","Submit supporting files","Check requirements","See why","Know what to do"][i]}</span></div>)}</div><div className="trust"><ShieldCheck/><div><b>Evidence-first decisions</b><p>AI can assist with understanding documents, while deterministic rules remain authoritative.</p></div><LockKeyhole/><div><b>Traceable by design</b><p>Important findings can be connected back to their source evidence.</p></div></div></section></>}
 {step==="info"&&<Workspace title="Applicant information" kicker="STEP 01" icon={<Users/>}><div className="form"><label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Preethika Amulya Sahithi"/></label><label>Date of birth<input type="date" value={dob} onChange={e=>setDob(e.target.value)}/></label><label>Annual income (₹)<input type="number" value={income} onChange={e=>setIncome(e.target.value)} placeholder="e.g. 280000"/></label><label>Current residence<input value={residence} onChange={e=>setResidence(e.target.value)} placeholder="City / district"/></label></div>{error&&<Error text={error}/>}<Actions back={()=>setStep("home")} next={start} text={busy?"Creating…":"Continue to evidence"}/></Workspace>}
 {step==="evidence"&&<Workspace title="Supporting evidence" kicker="STEP 02" icon={<UploadCloud/>}><label className="drop"><input type="file" multiple accept=".pdf,.png,.jpg,.jpeg" onChange={e=>setFiles(Array.from(e.target.files||[]))}/><UploadCloud size={40}/><b>Choose evidence files</b><span>PDF, JPG or PNG • up to 10 MB each</span></label>{files.map(f=><div className="file" key={f.name}><FileText/><span>{f.name}<small>{Math.round(f.size/1024)} KB</small></span><Check/></div>)}{error&&<Error text={error}/>}<Actions back={()=>setStep("info")} next={uploadAndProcess} text={busy?"Processing actual evidence…":"Upload & process evidence"}/></Workspace>}
 {step==="assessment"&&result&&<Workspace title="Evidence intelligence" kicker="STEP 03" icon={<FileText/>}><div className="actual"><div><b>Application</b><strong>{result.id}</strong><span>Fresh application created from your input</span></div><div><b>Documents received</b><strong>{result.documents.length}</strong><span>{result.documents.map(d=>d.filename).join(", ")}</span></div><div><b>Extraction status</b><strong>Completed</strong><span>Confidence recorded by processing layer</span></div></div><div className="trace"><AlertTriangle size={18}/><span>The evidence is processed from the files you submitted. Verification and eligibility remain separate steps.</span></div><Actions back={()=>setStep("evidence")} next={()=>{setStep("decision")}} text="View assessment"/></Workspace>}
 {step==="decision"&&result&&<main className="workspace"><Stepper n={4}/><div className={"banner "+result.decision.toLowerCase()}><div className="circle">{result.decision==="PROCEED"?<Check/>:<AlertTriangle/>}</div><div><small>APPLICATION DECISION</small><h1>{result.decision==="PROCEED"?"Sufficient evidence to proceed":result.decision==="NOT_SATISFIED"?"Condition not satisfied":result.decision==="ADDITIONAL_EVIDENCE_REQUIRED"?"Additional evidence required":"Human review required"}</h1><p>{result.reason}</p></div></div><div className="decisionGrid"><section className="panel"><h3>Decision trace</h3>{result.trace.map((t,i)=><div className="req" key={i}><div className="check"><Check/></div><div><b>{t.requirement}</b><p>{t.evidence} → {t.fact}</p><small>{t.rule} → {t.result}</small></div></div>)}</section><section className="panel next"><small>NEXT ACTION</small><h2>{result.decision==="PROCEED"?"Application can proceed":"Resolve the current blocker"}</h2><p>{result.decision==="PROCEED"?"No additional action is required at this stage.":"Follow the requirement shown in the trace. If uncertainty remains, a reviewer will handle it."}</p>{result.decision==="HUMAN_REVIEW_REQUIRED"&&<button className="primary" onClick={review}>Open reviewer portal <ArrowRight/></button>}</section></div><button className="secondary" onClick={()=>setStep("home")}>Start another application</button></main>}
 {step==="review"&&<Reviewer/>}
 <footer>ClearGov Nexus <span>Evidence-first • Explainable • Human-centred</span></footer></div>
}
function Workspace(p:any){return <main className="workspace"><Stepper n={p.kicker==="STEP 01"?1:p.kicker==="STEP 02"?2:3}/><section className="panel main"><div className="head"><div><small>{p.kicker}</small><h1>{p.title}</h1><p>Work with the actual application data and evidence you provide.</p></div>{p.icon}</div>{p.children}</section></main>}
function Stepper({n}:{n:number}){return <div className="stepper">{["Information","Evidence","Assessment","Decision","Next action"].map((x,i)=><div className={i+1===n?"active":""} key={x}><span>{i+1}</span>{x}</div>)}</div>}
function Actions({back,next,text}:{back:any,next:any,text:string}){return <div className="actions"><button className="secondary" onClick={back}>Back</button><button className="primary" onClick={next}>{text}<ArrowRight/></button></div>}
function Error({text}:{text:string}){return <div className="error"><AlertTriangle size={17}/>{text}</div>}
function Reviewer(){const [cases,setCases]=useState<any[]>([]);const [loaded,setLoaded]=useState(false);async function load(){const r=await fetch(API+"/api/reviewer/queue");setCases(await r.json());setLoaded(true)}return <main className="workspace"><div className="reviewHead"><div><small>REVIEWER PORTAL</small><h1>Human attention queue</h1><p>Cases where automation cannot safely produce an authoritative decision.</p></div><button className="secondary" onClick={load}>{loaded?"Refresh queue":"Load queue"}</button></div><section className="panel queue">{loaded&&cases.length===0?<div className="empty">No human-review cases have been created yet. Submit an application that produces uncertainty to populate this queue.</div>:cases.map(c=><div className="case" key={c.id}><b>{c.id}</b><h3>{c.applicant.name}</h3><p>{c.reason}</p><span>HUMAN REVIEW REQUIRED</span></div>)}</section></main>}
createRoot(document.getElementById("root")!).render(<App/>);
